### PR TITLE
Add fix for mpi4py version 4

### LINKED ISSUE #80: MUSIC Python extension and mpi4py 4
I've noticed that the latest version (4) of the mpi4py package is not compatible with the latest release of MUSIC (1.2.1 if I'm not mistaken). The write-up of the issue is available [here](https://github.com/neuronsimulator/nrn/issues/3095#issuecomment-2391128342). Note that version 3.x of mpi4py is compatible with MUSIC, however, with Python 3.13 just around the corner, and mpi4py 3.x [not being supported](https://github.com/mpi4py/mpi4py/issues/555) on that Python version (at least not without applying some workarounds), I am wondering if there is a plan for a version of MUSIC compatible with mpi4py version 4?

### PR DESCRIPTION
**Pull request by JCGoran**
Should fix #80.

### CODE REVIEW

**Review by alkino — APPROVED** [review]

**Comment by pramodk** [comment]
Hello @mdjurfeldt,

We are trying to get new NEURON 9.0 release with Python 3.13 and it would be very helpfult to have this PR merged. 

If you have some time, could you take a look and merge this?

**Comment by mdjurfeldt** [comment]
Hi @JCGoran and @pramodk , sorry for slow response.

I'm a bit confused by this PR.

Shouldn't it be:

#include <mpi.h>
    
#if (MPI_VERSION < 3) && !defined(PyMPI_HAVE_MPI_Message)
typedef void *PyMPI_MPI_Message;
#define MPI_Message PyMPI_MPI_Message
#endif
    
#if (MPI_VERSION < 4) && !defined(PyMPI_HAVE_MPI_Session)
typedef void *PyMPI_MPI_Session;
#define MPI_Session PyMPI_MPI_Session
#endif

which is what mpi4py people are suggesting [here](https://github.com/mpi4py/mpi4py/issues/525#issuecomment-2256633404)?

**Comment by mdjurfeldt** [comment]
Ah... sorry. It is their *fix* (which I linked to) which is causing the problem (a collision with MUSIC:s fix) and which your PR avoids, right?

**Comment by JCGoran** [comment]
Hi @mdjurfeldt, the fix is more or less verbatim from https://github.com/mpi4py/mpi4py/issues/525#issuecomment-2256633404. I've tested this PR on NEURON w/ Python 3.13 and mpi4py version 4, and it works fine for our particular use-case.

**Comment by mdjurfeldt** [comment]
Well, my problem is that I need to make sure that it will work on all cases. I'm currently trying to understand the situation. You are welcome to help me. What I *can* say is that your PR is not a verbatim copy the comment you refer to. You have modified the version to compare to to 4 for MPI_Message. They compare to version 4 for MPI_Session.

**Comment by mdjurfeldt** [comment]
Does their (verbatim, not this PR) mpi-compat.h solve your problem?

**Comment by JCGoran** [comment]
Sorry, not sure I follow; if I compare the file from this PR:

- https://github.com/INCF/MUSIC/blob/e5bf00b7dff460958a845254a9eb39ccece34ff6/pymusic/mpi_compat.h

with the one referenced by the comment:

- https://github.com/mpi4py/mpi4py/blob/master/demo/wrap-cython/mpi-compat.h

I don't see a difference between the two (modulo include guard/whitespace/comments, which don't affect functionality)?

**Comment by mdjurfeldt** [comment]
Sorry. I misread the commit. You are completely right. Sorry for all confusion. :) I'll merge it now.

**Pull request merged**
